spring.application.name=cryptoFlow
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/crypto_flow_db
spring.datasource.username=postgres
spring.datasource.password=11111111
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml